### PR TITLE
fix(language-server): auto complete complex utility values

### LINKED ISSUE #71: Resolved auto complete is incorrect for utilities
### Description

Adding utility such as `width` displays only the static keys. The names of the tokens from a `...theme('sizes')` are not shown.

Image

Image

### Link to Reproduction

NA

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

_No response_

### Panda CSS Version

0.53.0

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

@astahmer could you give me a pointer where this would be located in code? Thank you!

### PR DESCRIPTION
**Pull request by cgatian**
Closes #71

## 📝 Description

Extract token values from utility functions that contain token references.

🎊 
fixaroo

### CODE REVIEW

File: packages/language-server/src/completion-provider.ts [hunk 1]
```diff
@@ -151,13 +151,28 @@ export const getCompletionFor = ({
       category = utility.values
     } else if (typeof utility.values === 'function') {
       // values: (theme) => { ...theme("spacing") }
-      const record = ctx.utility.getPropertyValues(utility, (cat) => {
-        category = cat
-        return cat
+      const record = ctx.utility.getPropertyValues(utility, (key) => {
+        return `types:Tokens["${key}"]`
```
Comment (cgatian) [inline packages/language-server/src/completion-provider.ts:155]: Used similar function from panda/core

https://github.com/chakra-ui/panda/blob/465eb9c480be3e5ba8e232f06b346e1f1ab5b474/packages/core/src/utility.ts#L340

**Review by astahmer — APPROVED** [review]
awesome thanks! btw feel free to assign me as a reviewer otherwise I'll not get the PR notifications
